Contact.create!([
  {first_name: "Kenton", last_name: "Satterfield", email: "jeyca_becker@metz.com", phone_number: "747-594-0287", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ross", last_name: "Haag", email: "alfred@gutmann.info", phone_number: "(862) 930-7550", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Sally", last_name: "Bauch", email: "alvina_rodriguez@prosacco.net", phone_number: "(756) 308-1995", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Crystal", last_name: "Simonis", email: "kayley_wolff@batz.com", phone_number: "1-942-860-0824", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Minnie", last_name: "Lind", email: "yazmin_willms@davisokon.co", phone_number: "874.923.0390", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Anthony", last_name: "Halvorson", email: "jaron.abernathy@wisokyblick.io", phone_number: "1-227-021-7908", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Jan", last_name: "Kunde", email: "reva@kiehn.info", phone_number: "1-260-813-7507", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Marilyne", last_name: "Lowe", email: "alison.berge@braunfahey.com", phone_number: "256.179.0663", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Name", last_name: "Howe", email: "rosalee@ricerutherford.net", phone_number: "598.893.3776", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Julian", last_name: "Satterfield", email: "walton_fadel@hegmannshanahan.io", phone_number: "495-842-5086", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Gertrude", last_name: "Nicolas", email: "robbie@gibson.io", phone_number: "104.035.8617", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Joanny", last_name: "Hilpert", email: "tia.gulgowski@haley.info", phone_number: "623-805-2404", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Hassan", last_name: "Heaney", email: "brain@herman.co", phone_number: "(721) 975-2035", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Waldo", last_name: "Adams", email: "kaley@haleynader.name", phone_number: "904-266-7218", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Dock", last_name: "Lemke", email: "johnpaul_dare@stroman.com", phone_number: "1-382-167-4578", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Cleo", last_name: "Blanda", email: "ferne.weber@hodkiewicz.org", phone_number: "162.868.4490", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Wilton", last_name: "Satterfield", email: "devon.gerhold@jones.info", phone_number: "694-271-1445", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Oda", last_name: "Crooks", email: "hortense.buckridge@lindswaniawski.io", phone_number: "396-819-4611", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Octavia", last_name: "Howell", email: "marta.oconner@effertzmacgyver.biz", phone_number: "(532) 533-0356", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Sydnie", last_name: "McKenzie", email: "fermin_hilll@tromp.name", phone_number: "893.914.8571", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ruben", last_name: "Schiller", email: "ada.herman@nikolaus.biz", phone_number: "340-953-5183", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Corine", last_name: "White", email: "juwan@boscoblock.co", phone_number: "(797) 484-9089", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ruthe", last_name: "Rutherford", email: "oda.connelly@hegmann.io", phone_number: "1-314-598-0769", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Augustus", last_name: "Crona", email: "spencer@collins.biz", phone_number: "(617) 182-6493", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lauretta", last_name: "Conn", email: "brendon.bernier@muellercorkery.name", phone_number: "1-977-761-8603", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Yadira", last_name: "Ullrich", email: "marcelino@connelly.info", phone_number: "202-854-8123", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Andrew", last_name: "Spinka", email: "jayce.kunze@kutch.info", phone_number: "927.867.4969", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Constance", last_name: "Gusikowski", email: "florida.torp@von.org", phone_number: "836.080.3875", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Rose", last_name: "Zulauf", email: "olaf@dooley.biz", phone_number: "238.923.3113", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ricardo", last_name: "Leffler", email: "elva@bergstrom.info", phone_number: "1-752-220-7982", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Rupert", last_name: "Fisher", email: "briana_lindgren@lubowitzflatley.name", phone_number: "1-385-811-2125", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Chadrick", last_name: "Upton", email: "mittie_botsford@morarortiz.info", phone_number: "401-224-9481", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Baby", last_name: "Weimann", email: "percival@kuhic.info", phone_number: "579-534-1492", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Aidan", last_name: "Schaden", email: "remington@douglas.co", phone_number: "259.044.5789", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ben", last_name: "Boehm", email: "alexandro@abshire.io", phone_number: "711.855.7636", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Dax", last_name: "Legros", email: "jett@bartoletti.co", phone_number: "1-789-924-4208", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Hilma", last_name: "Beer", email: "tierra.jakubowski@hermannkertzmann.com", phone_number: "536.895.0252", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Leonard", last_name: "Sipes", email: "geo@kertzmann.org", phone_number: "1-731-251-6188", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Mark", last_name: "Bartell", email: "jaiden@reingeroconnell.io", phone_number: "940.530.5097", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Beryl", last_name: "Nicolas", email: "jamal@adamsgoodwin.com", phone_number: "910.310.5960", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Derek", last_name: "Renner", email: "carole_haag@mohrbarrows.name", phone_number: "222.945.3073", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Reuben", last_name: "Trantow", email: "jackie@schneider.com", phone_number: "(489) 948-6110", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Marianna", last_name: "Hettinger", email: "jerel@huels.net", phone_number: "156.847.0404", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Viola", last_name: "Price", email: "jada@considine.com", phone_number: "(277) 575-1632", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Bella", last_name: "McKenzie", email: "mittie.schmeler@ziemann.io", phone_number: "1-484-098-8868", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "William", last_name: "Langosh", email: "zion@boehm.info", phone_number: "(391) 362-3717", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Barton", last_name: "Lakin", email: "jody@feest.net", phone_number: "1-425-297-1696", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Arielle", last_name: "Krajcik", email: "roie@denesik.com", phone_number: "955-401-2949", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Heath", last_name: "Kertzmann", email: "margarett_legros@sanfordcollier.name", phone_number: "214-815-6792", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Shad", last_name: "Cormier", email: "margaretta@emarddenesik.biz", phone_number: "1-299-692-7859", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Agustina", last_name: "Renner", email: "ron@greenholtheller.io", phone_number: "266-389-3841", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Michaela", last_name: "O'Reilly", email: "jonatan.parisian@howelakin.name", phone_number: "(164) 919-2583", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Hector", last_name: "Wilderman", email: "lavina_kihn@nicolas.net", phone_number: "643.696.4112", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Janie", last_name: "Gutkowski", email: "clemens@gerholdkeler.co", phone_number: "1-246-464-3519", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Luis", last_name: "O'Kon", email: "destini.skiles@lang.biz", phone_number: "(941) 787-3614", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Irma", last_name: "Satterfield", email: "blaze_ebert@kerlukeokon.name", phone_number: "1-451-734-2988", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Keagan", last_name: "Oberbrunner", email: "winifred.lehner@nadergoldner.info", phone_number: "938-480-3467", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Sterling", last_name: "Leuschke", email: "louie_macejkovic@halvorsonhilpert.net", phone_number: "1-630-614-4498", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Maverick", last_name: "Weimann", email: "tyshawn.konopelski@langworth.name", phone_number: "1-670-288-4224", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Sonya", last_name: "Bogisich", email: "ellen@dubuque.name", phone_number: "1-348-758-7268", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Kay", last_name: "MacGyver", email: "kristoffer@gislasontowne.biz", phone_number: "1-341-867-0227", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Damian", last_name: "Robel", email: "keanu@hayes.co", phone_number: "416-364-7448", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Grayson", last_name: "Hintz", email: "lori.fisher@west.info", phone_number: "242.447.2724", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Percy", last_name: "Klein", email: "frederic_weimann@jaskolski.org", phone_number: "178-148-3568", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Reggie", last_name: "Funk", email: "shaun.wolf@wiegand.biz", phone_number: "274-294-7634", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Darrell", last_name: "Wunsch", email: "muhammad_abbott@gottliebchristiansen.io", phone_number: "1-908-901-7294", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Darrell", last_name: "Rolfson", email: "giuseppe.gibson@ebert.org", phone_number: "1-187-631-7535", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Milford", last_name: "Eichmann", email: "ernestina@christiansengutkowski.io", phone_number: "(881) 630-3947", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lisette", last_name: "Bahringer", email: "alexys_stark@wisoky.com", phone_number: "703.739.0802", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Darren", last_name: "Cruickshank", email: "benjamin_bogisich@reingerhickle.org", phone_number: "(879) 178-8181", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Soledad", last_name: "Von", email: "brittany_ebert@ohara.net", phone_number: "(286) 452-2691", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Linwood", last_name: "Schmitt", email: "clementina@schuppe.biz", phone_number: "400-713-1119", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Marisa", last_name: "Hyatt", email: "rogelio.armstrong@willstiedemann.org", phone_number: "693.906.5131", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Asha", last_name: "Bode", email: "gail.rippin@tillman.biz", phone_number: "580.800.7749", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Clint", last_name: "Fisher", email: "emery_johns@stokes.org", phone_number: "958-961-3934", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Tressa", last_name: "Hane", email: "robert@mullerherzog.net", phone_number: "(551) 522-9283", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Alanna", last_name: "Fisher", email: "lindsey@bradtke.co", phone_number: "171.100.5294", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Aidan", last_name: "Kuphal", email: "emmalee_gerlach@hirthesawayn.biz", phone_number: "1-211-329-0257", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Maurine", last_name: "Lesch", email: "barry_cruickshank@krajcik.name", phone_number: "(878) 670-2000", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Delaney", last_name: "Brown", email: "cletus@bashirian.net", phone_number: "1-538-503-8479", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lavonne", last_name: "McLaughlin", email: "queen.mills@keler.info", phone_number: "1-636-113-4715", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Dorris", last_name: "Koelpin", email: "erik_skiles@bashiriannitzsche.co", phone_number: "1-263-237-8140", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Francesco", last_name: "Kunde", email: "merritt@dickenskoepp.net", phone_number: "737.436.5523", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Kamille", last_name: "Mueller", email: "alayna.dickens@welchortiz.com", phone_number: "356-496-4722", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Bobby", last_name: "Kuhic", email: "terry@predovic.com", phone_number: "(747) 258-2162", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Karen", last_name: "Franecki", email: "alexane@muller.com", phone_number: "1-365-483-9987", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Arnaldo", last_name: "Schneider", email: "leora@goldner.net", phone_number: "1-726-772-0759", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Jonathon", last_name: "Jerde", email: "eriberto@ernser.info", phone_number: "1-972-191-0832", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Belle", last_name: "Schulist", email: "macey@corwin.io", phone_number: "(153) 957-6385", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Christophe", last_name: "Farrell", email: "hallie@littelhilll.info", phone_number: "424.482.4466", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lorena", last_name: "Kreiger", email: "roosevelt@howelynch.com", phone_number: "1-699-059-1664", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Jeramy", last_name: "Larson", email: "chester@kunde.com", phone_number: "(251) 801-1053", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Clemmie", last_name: "Huel", email: "wendy.carter@williamson.biz", phone_number: "825-436-2316", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Annette", last_name: "Gleason", email: "sister@deckowlockman.info", phone_number: "368-266-3911", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Camylle", last_name: "Pacocha", email: "brittany_blick@weinatbarton.net", phone_number: "1-686-613-5647", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Gail", last_name: "Langosh", email: "kailee_dibbert@kulas.com", phone_number: "1-161-779-4982", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Jazmyn", last_name: "Hermann", email: "neha@satterfield.net", phone_number: "1-403-734-0405", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Loy", last_name: "Braun", email: "kay@wolf.io", phone_number: "(163) 699-2232", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Herman", last_name: "Koch", email: "marta_lehner@damoresawayn.info", phone_number: "196-065-9920", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Imogene", last_name: "Gislason", email: "jacey@reichel.name", phone_number: "(277) 858-9373", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil}
])
