User.create!([
  {email: "khoa@msn.com", encrypted_password: "$2a$10$Zg7po9NRn4JrUAZk2M/JnOYP1h2XLfOcULZjCM4odJUdalgHKgRxO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-10-13 16:09:59", last_sign_in_at: "2015-10-13 16:09:59", current_sign_in_ip: "::1", last_sign_in_ip: "::1"}
])
Contact.create!([
  {first_name: "June", last_name: "Rippin", email: "libbie@predovicmacejkovic.com", phone_number: "200-761-9067", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Stella", last_name: "Breitenberg", email: "ruth_rempel@satterfieldkreiger.co", phone_number: "(536) 139-9846", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Paula", last_name: "Pacocha", email: "beryl.reichert@aufderhar.io", phone_number: "(185) 473-0294", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Brigitte", last_name: "Hoppe", email: "adeline@purdy.net", phone_number: "379.444.5585", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Graham", last_name: "Bergnaum", email: "chase@maggio.info", phone_number: "(753) 317-6546", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Monty", last_name: "Streich", email: "erna.farrell@lueilwitzfay.io", phone_number: "1-125-501-5801", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Rossie", last_name: "Bogisich", email: "reynold@paucekstokes.org", phone_number: "781.821.1139", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Demario", last_name: "Ankunding", email: "rickey@jakubowskiprosacco.biz", phone_number: "(943) 481-6421", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Carlotta", last_name: "Armstrong", email: "justyn_mccullough@leffler.io", phone_number: "(714) 624-3922", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Sandrine", last_name: "Rogahn", email: "eldon@hammes.io", phone_number: "957.821.9713", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Stan", last_name: "Boyer", email: "cruz@tremblay.io", phone_number: "1-697-038-8869", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Vita", last_name: "Walsh", email: "prince.maggio@kub.io", phone_number: "937.055.4944", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Clay", last_name: "Christiansen", email: "kelsi_blick@johns.co", phone_number: "1-790-290-8674", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Barton", last_name: "Cole", email: "darrick@konopelski.biz", phone_number: "1-504-267-9583", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Kamille", last_name: "Turcotte", email: "therese@friesen.org", phone_number: "1-614-464-0915", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Libbie", last_name: "Doyle", email: "aracely.durgan@moriettekohler.info", phone_number: "(904) 144-6850", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Maya", last_name: "Abshire", email: "chandler_oconner@jastdurgan.name", phone_number: "199-703-0024", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Juvenal", last_name: "Jenkins", email: "kim@satterfield.co", phone_number: "439-006-1045", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Adonis", last_name: "Hackett", email: "daphne.bogan@moriettebrown.com", phone_number: "240-670-1352", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Gerda", last_name: "Haag", email: "katrina@abbott.io", phone_number: "656-389-6098", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ozzie", last_name: "Bode", email: "alene@heel.com", phone_number: "736-114-9211", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Luisa", last_name: "Lubowitz", email: "lura_olson@kutch.info", phone_number: "1-698-988-2219", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Joanny", last_name: "Lemke", email: "aurore_dicki@krisvonrueden.net", phone_number: "1-210-007-5860", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lillian", last_name: "Collier", email: "quinton@pagackshlerin.net", phone_number: "401.643.7087", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Janick", last_name: "McDermott", email: "kaya@morarreichel.co", phone_number: "1-758-629-9974", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Gus", last_name: "Quigley", email: "audrey.cummerata@johnston.info", phone_number: "1-290-115-3898", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Julien", last_name: "Sanford", email: "eloisa@herzogquigley.co", phone_number: "679.442.1580", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Jacklyn", last_name: "Heidenreich", email: "berry@kulas.io", phone_number: "(987) 969-9172", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Garnett", last_name: "Hoeger", email: "margie@hermiston.biz", phone_number: "(569) 493-7614", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Angelo", last_name: "Beahan", email: "rozella@lindgren.name", phone_number: "772.745.5227", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Jacques", last_name: "Cartwright", email: "haleigh_ward@douglas.info", phone_number: "1-986-712-7782", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Julio", last_name: "McClure", email: "stephany@cormier.net", phone_number: "360.094.0404", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Petra", last_name: "Auer", email: "mauricio@dickens.co", phone_number: "430-583-3417", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Reba", last_name: "Osinski", email: "devante@rice.com", phone_number: "981-211-2672", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Branson", last_name: "Kulas", email: "aileen_kiehn@maggio.net", phone_number: "820.173.9481", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Benjamin", last_name: "Pouros", email: "annetta.schuster@andersonthiel.biz", phone_number: "196-307-4832", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Alicia", last_name: "Rau", email: "robyn_thiel@jastweimann.com", phone_number: "(598) 872-3962", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Dashawn", last_name: "Cruickshank", email: "sydnee.vonrueden@dickens.name", phone_number: "394.452.9877", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Aiden", last_name: "Boehm", email: "cierra_trantow@ko.net", phone_number: "379-659-8718", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Muriel", last_name: "Mohr", email: "albina@kemmerzboncak.net", phone_number: "1-902-157-9050", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Amara", last_name: "Weimann", email: "grayson@parisian.name", phone_number: "1-967-813-0030", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Brittany", last_name: "Kuhic", email: "mia.schmitt@lubowitz.com", phone_number: "845-853-9397", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lucious", last_name: "O'Hara", email: "alena@walsh.co", phone_number: "560-613-7273", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Hilbert", last_name: "Bartoletti", email: "aleen@weimann.io", phone_number: "1-832-209-6447", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Helene", last_name: "Romaguera", email: "winston@robel.co", phone_number: "448.365.7155", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Tremayne", last_name: "Mitchell", email: "jackson.mann@fadel.biz", phone_number: "1-657-387-6391", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Demond", last_name: "Stokes", email: "jena@reingerromaguera.io", phone_number: "848-397-6973", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Dolores", last_name: "Cruickshank", email: "kurt.thiel@bahringer.name", phone_number: "1-931-680-3327", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Zachery", last_name: "Cummerata", email: "teagan@davis.org", phone_number: "128.918.9887", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Tristin", last_name: "Champlin", email: "elnora@oconnellhirthe.biz", phone_number: "(539) 392-4429", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Otho", last_name: "Reinger", email: "irwin@gislasonlangworth.biz", phone_number: "888.256.7338", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Myron", last_name: "Hand", email: "bobby@andersonhackett.org", phone_number: "1-424-211-6404", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Cathryn", last_name: "Barton", email: "deie@mosciskibahringer.io", phone_number: "333.920.6463", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Noe", last_name: "Borer", email: "kaylee.vandervort@welchstehr.info", phone_number: "1-517-303-3293", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Rafael", last_name: "Williamson", email: "dashawn_lockman@little.org", phone_number: "574-054-8835", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Adell", last_name: "Sawayn", email: "emmet_ryan@pourospredovic.name", phone_number: "219-154-5712", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Elisa", last_name: "McKenzie", email: "tyshawn@willms.info", phone_number: "323.699.6425", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Mitchel", last_name: "Hodkiewicz", email: "gracie@skileteuber.io", phone_number: "1-587-335-2547", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Wilmer", last_name: "Gerlach", email: "myriam.greenfelder@hauckpfeffer.info", phone_number: "(279) 913-6414", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Loma", last_name: "Turcotte", email: "freda.marvin@schmidt.net", phone_number: "182.347.7236", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lucinda", last_name: "Koss", email: "santa_vandervort@vonruedenwalter.info", phone_number: "(579) 012-5091", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Mary", last_name: "Johnson", email: "dora@dietrichleffler.net", phone_number: "1-433-682-6163", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Libby", last_name: "Mohr", email: "keyon.wintheiser@luettgen.biz", phone_number: "145-047-0322", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Abel", last_name: "Hodkiewicz", email: "vergie.price@lowe.io", phone_number: "408-609-8166", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Delta", last_name: "Pollich", email: "mariah@maggiogerhold.info", phone_number: "(561) 174-5836", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ryder", last_name: "West", email: "amir_sipes@stammmckenzie.info", phone_number: "(860) 186-4764", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Andreane", last_name: "Gibson", email: "ernest@west.name", phone_number: "305-877-2395", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Nichole", last_name: "Larson", email: "cody@bergnaum.net", phone_number: "159-510-8498", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Gussie", last_name: "Jenkins", email: "caandra.mcclure@murazikjacobi.net", phone_number: "393-722-1363", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Kolby", last_name: "Keebler", email: "beverly.stark@ornkovacek.io", phone_number: "(646) 383-2743", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Jazlyn", last_name: "Lemke", email: "eloisa@mueller.com", phone_number: "820.962.9286", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Rod", last_name: "Jakubowski", email: "zachary@schinnerlabadie.info", phone_number: "1-271-566-1764", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Bert", last_name: "Legros", email: "cooper.schulist@pouros.org", phone_number: "452-562-2390", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Verda", last_name: "Wilderman", email: "alayna_hyatt@sawayn.net", phone_number: "1-770-847-4260", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Reilly", last_name: "Hayes", email: "cesar_considine@gerlach.info", phone_number: "(751) 120-3093", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ed", last_name: "Stoltenberg", email: "garnet@zieme.name", phone_number: "406.835.0942", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Micah", last_name: "Bailey", email: "emely.auer@hayestoy.biz", phone_number: "322.495.0307", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Lester", last_name: "Lehner", email: "faye@bruen.name", phone_number: "1-400-988-0270", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ollie", last_name: "Hettinger", email: "dolly@huels.io", phone_number: "1-657-880-1898", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Alfonzo", last_name: "Kerluke", email: "lexie.ryan@ullrich.info", phone_number: "500.499.4994", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Brent", last_name: "Beer", email: "martin_sawayn@ernser.io", phone_number: "372-431-1056", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Eliza", last_name: "Satterfield", email: "saige@schmelerswift.org", phone_number: "740-005-2162", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Osvaldo", last_name: "Marvin", email: "nicole@stamm.com", phone_number: "(941) 597-1816", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Chance", last_name: "Franecki", email: "antoinette@kilback.info", phone_number: "573-531-7841", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Juanita", last_name: "Botsford", email: "ethyl_smitham@cruickshank.name", phone_number: "948-943-4034", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Trever", last_name: "Conn", email: "harold@kuvalis.net", phone_number: "1-972-862-9043", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Neil", last_name: "Baumbach", email: "keshawn@turcotte.info", phone_number: "648-496-3283", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Elmore", last_name: "Greenfelder", email: "betsy_rodriguez@pfannerstillkovacek.net", phone_number: "788-158-2801", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Devon", last_name: "Bergnaum", email: "stanton_hermann@bartell.org", phone_number: "451.169.7930", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Loma", last_name: "Bode", email: "veda.skiles@durgan.info", phone_number: "543.165.2559", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Agustin", last_name: "Monahan", email: "wilber@rowe.org", phone_number: "653.486.7013", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Crystal", last_name: "Nienow", email: "ike@hilll.info", phone_number: "1-997-550-2604", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Eula", last_name: "Boyle", email: "lenora@bruenreichert.com", phone_number: "953-514-1477", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ozzie", last_name: "Schuster", email: "kennith.emard@maggio.net", phone_number: "164.788.3180", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Ruben", last_name: "Schroeder", email: "hailie_stehr@prohaska.info", phone_number: "131-455-0431", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil},
  {first_name: "Easter", last_name: "Dickens", email: "cathrine@stiedemannturner.name", phone_number: "(791) 393-9367", middle_name: nil, bio: nil, latitude: nil, longitude: nil, address: nil, user_id: nil}
])
